### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by alexlevy0** [mrpatiwi/ReactNativeTS#21]
C:\Dev\ReactNativeTS>yarn run build
yarn run v0.27.5
$ node node_modules/.bin/rimraf build
C:\Dev\DEV-Wavy\ReactNativeTS\node_modules\.bin\rimraf:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
                ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by vandervidi** [comment]
@alexlevy0  i have the same error. Did you manage to fix that?

**Comment by futurfutur** [comment]
same there

**Comment by MartinOrtiz** [comment]
has this been fixed?
